### ISSUE TITLE
Crash when harvesting The Aether crystal trees

### ISSUE THREAD

**Issue by MrQueeba** [FakeDomi/UniQ#3]
There is an incompatibility between the 1.7.10 version of this mod and trees with crystal leaves from The Aether (legacy, not Aether II) where when harvesting the tree the game crashes with a NullPointerException. Issue is most easily reproduced if TreeCapitator is installed, although I have reproduced it without the mod.
[crash-2024-05-14_15.26.07-server.txt](https://github.com/LoliKingdom/UniQ/files/15313076/crash-2024-05-14_15.26.07-server.txt)

**Comment by MrQueeba** [comment]
Figured out the issue: in the ResourceUnifier class's getPreferredStack method, there is no check for whether identifier is null. I added the following immediately after identifier is defined and the game no longer crashes:

if (identifier == null)
{
    return stack;
}

**Comment by danRP408** [comment]
colud you share your fixed build?
